version: '3.7'

services:
    seddit_backend:
        stdin_open: true
        build: ./backend
        container_name: seddit_backend
        restart: always
        expose:
         - 5001
        ports:
         - 5001:5001
        volumes:
         - ./backend:/usr/src/seddit 

    seddit_frontend:
        stdin_open: true
        container_name: seddit_frontend
        build: ./frontend
        expose:
         - 3001
        ports:
         - 3001:3001
        volumes:
         - ./frontend:/usr/src/seddit/frontend
        links:
        - "seddit_backend:seddit_backend"

    nginx:
        image: nginx:1.13 # this will use the latest version of 1.13.x
        ports:
          - '80:80' # expose 80 on host and sent to 80 in container
        depends_on: 
          - seddit_frontend
        volumes:
          - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
